// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107142232_MdfyTenant")]
    partial class MdfyTenant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_no");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("MemberNo")
                        .IsUnique()
                        .HasDatabaseName("ix_members_member_no");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_members_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("members", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_member_activity_log");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_member_activity_log_action_created_at");

                    b.HasIndex("MemberId", "CreatedAt")
                        .HasDatabaseName("ix_member_activity_log_member_id_created_at");

                    b.ToTable("member_activity_log", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetBalance", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("AssetCode")
                        .HasColumnType("text")
                        .HasColumnName("asset_code");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberId", "AssetCode")
                        .HasName("pk_member_asset_balance");

                    b.ToTable("member_asset_balance", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AfterBalance")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_balance");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("amount");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_code");

                    b.Property<decimal>("BeforeBalance")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_member_asset_ledger");

                    b.HasIndex("MemberId", "AssetCode", "CreatedAt")
                        .HasDatabaseName("ix_member_asset_ledger_member_id_asset_code_created_at");

                    b.ToTable("member_asset_ledger", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberPointBalance", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberId")
                        .HasName("pk_member_point_balance");

                    b.ToTable("member_point_balance", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberPointLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AfterBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("after_balance");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BeforeBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("before_balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_member_point_ledger");

                    b.HasIndex("MemberId", "CreatedAt")
                        .HasDatabaseName("ix_member_point_ledger_member_id_created_at");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_member_point_ledger_reference_type_reference_id");

                    b.ToTable("member_point_ledger", "public");
                });

            modelBuilder.Entity("Domain.Nodes.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_node");

                    b.ToTable("node", "public");
                });

            modelBuilder.Entity("Domain.Nodes.NodeRelation", b =>
                {
                    b.Property<Guid>("AncestorNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_node_id");

                    b.Property<Guid>("DescendantNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_node_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("AncestorNodeId", "DescendantNodeId")
                        .HasName("pk_node_relation");

                    b.HasIndex("DescendantNodeId")
                        .HasDatabaseName("ix_node_relation_descendant_node_id");

                    b.ToTable("node_relation", "public");
                });

            modelBuilder.Entity("Domain.Security.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups", "public");
                });

            modelBuilder.Entity("Domain.Security.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permission_role_id");

                    b.ToTable("permission", "public");
                });

            modelBuilder.Entity("Domain.Security.PermissionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_code");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_assignments");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_permission_assignments_node_id");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_permission_assignments_permission_code");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_permission_assignments_tenant_id");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_permission_assignments_subject_type_subject_id");

                    b.ToTable("permission_assignments", "public");
                });

            modelBuilder.Entity("Domain.Security.ResourceNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_nodes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_resource_nodes_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_resource_nodes_tenant_id");

                    b.HasIndex("TenantId", "ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ux_resource_nodes_tenant_id_external_key");

                    b.ToTable("resource_nodes", "public");
                });

            modelBuilder.Entity("Domain.Security.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", "public");
                });

            modelBuilder.Entity("Domain.Security.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.HasKey("UserId", "GroupId")
                        .HasName("pk_user_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_user_groups_group_id");

                    b.HasIndex("UserId", "GroupId")
                        .HasDatabaseName("ix_user_groups_user_id_group_id");

                    b.ToTable("user_groups", "public");
                });

            modelBuilder.Entity("Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_code");

                    b.ToTable("tenants", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("HasPublicProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("has_public_profile");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Domain.Users.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Domain.Users.User.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Users.UserTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_tenants");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_tenants_tenant_id");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_tenants_user_id_tenant_id");

                    b.ToTable("user_tenants", "public");
                });

            modelBuilder.Entity("Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "public");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", "public");
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_members_users_user_id");
                });

            modelBuilder.Entity("Domain.Members.MemberActivityLog", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_activity_log_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetBalance", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_asset_balance_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetLedger", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_asset_ledger_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberPointBalance", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_point_balance_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberPointLedger", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_point_ledger_members_member_id");
                });

            modelBuilder.Entity("Domain.Nodes.NodeRelation", b =>
                {
                    b.HasOne("Domain.Nodes.Node", "AncestorNode")
                        .WithMany("Descendants")
                        .HasForeignKey("AncestorNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_relation_node_ancestor_node_id");

                    b.HasOne("Domain.Nodes.Node", "DescendantNode")
                        .WithMany("Ancestors")
                        .HasForeignKey("DescendantNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_relation_node_descendant_node_id");

                    b.Navigation("AncestorNode");

                    b.Navigation("DescendantNode");
                });

            modelBuilder.Entity("Domain.Security.Permission", b =>
                {
                    b.HasOne("Domain.Security.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_permission_role_role_id");
                });

            modelBuilder.Entity("Domain.Security.PermissionAssignment", b =>
                {
                    b.HasOne("Domain.Security.ResourceNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .HasConstraintName("fk_permission_assignments_resource_nodes_node_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Domain.Security.ResourceNode", b =>
                {
                    b.HasOne("Domain.Security.ResourceNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_resource_nodes_resource_nodes_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Security.UserGroup", b =>
                {
                    b.HasOne("Domain.Security.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_groups_groups_group_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_groups_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Users.UserTenant", b =>
                {
                    b.HasOne("Domain.Tenants.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenants_tenants_tenant_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("UserTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tenants_users_user_id");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Domain.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_role_roles_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_users_users_id");
                });

            modelBuilder.Entity("Domain.Nodes.Node", b =>
                {
                    b.Navigation("Ancestors");

                    b.Navigation("Descendants");
                });

            modelBuilder.Entity("Domain.Security.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Domain.Security.ResourceNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Security.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("UserGroups");

                    b.Navigation("UserTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
