// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116024404_AddSlot")]
    partial class AddSlot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Gaming.Draws.Draw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Algorithm")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("algorithm");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DerivedInput")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("derived_input");

                    b.Property<DateTime>("DrawAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draw_at");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_code");

                    b.Property<bool>("IsManuallyClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manually_closed");

                    b.Property<DateTime?>("ManualCloseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("manual_close_at");

                    b.Property<string>("ManualCloseReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("manual_close_reason");

                    b.Property<int?>("RedeemValidDays")
                        .HasColumnType("integer")
                        .HasColumnName("redeem_valid_days");

                    b.Property<DateTime>("SalesCloseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sales_close_at");

                    b.Property<DateTime>("SalesOpenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sales_open_at");

                    b.Property<string>("ServerSeed")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("server_seed");

                    b.Property<string>("ServerSeedHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("server_seed_hash");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WinningNumbersRaw")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("winning_numbers_raw");

                    b.HasKey("Id")
                        .HasName("pk_draws");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_draws_tenant_id_status");

                    b.ToTable("draws", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Draws.DrawAllowedTicketTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_template_id");

                    b.HasKey("Id")
                        .HasName("pk_draw_allowed_ticket_templates");

                    b.HasIndex("TenantId", "DrawId", "TicketTemplateId")
                        .IsUnique()
                        .HasDatabaseName("ix_draw_allowed_ticket_templates_tenant_id_draw_id_ticket_temp");

                    b.ToTable("draw_allowed_ticket_templates", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Draws.DrawEnabledPlayType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<string>("PlayTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("play_type_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_draw_enabled_play_types");

                    b.HasIndex("DrawId")
                        .HasDatabaseName("ix_draw_enabled_play_types_draw_id");

                    b.HasIndex("TenantId", "DrawId", "PlayTypeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_draw_enabled_play_types_tenant_id_draw_id_play_type_code");

                    b.ToTable("draw_enabled_play_types", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Draws.DrawPrizePoolItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<Guid?>("DrawId1")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id1");

                    b.Property<string>("PlayTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("play_type_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_draw_prize_pool_items");

                    b.HasIndex("DrawId")
                        .HasDatabaseName("ix_draw_prize_pool_items_draw_id");

                    b.HasIndex("DrawId1")
                        .HasDatabaseName("ix_draw_prize_pool_items_draw_id1");

                    b.HasIndex("TenantId", "DrawId", "PlayTypeCode", "Tier")
                        .IsUnique()
                        .HasDatabaseName("ix_draw_prize_pool_items_tenant_id_draw_id_play_type_code_tier");

                    b.ToTable("draw_prize_pool_items", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Entitlements.TenantGameEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<DateTime>("EnabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at_utc");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_game_entitlements");

                    b.HasIndex("TenantId", "GameCode")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_game_entitlements_tenant_game");

                    b.ToTable("tenant_game_entitlements", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Entitlements.TenantPlayEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<DateTime>("EnabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at_utc");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("PlayTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("play_type_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_play_entitlements");

                    b.HasIndex("TenantId", "GameCode", "PlayTypeCode")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_play_entitlements_tenant_game_play");

                    b.ToTable("tenant_play_entitlements", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.PrizeAwards.PrizeAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_at");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_code");

                    b.Property<int>("LineIndex")
                        .HasColumnType("integer")
                        .HasColumnName("line_index");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_count");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("PlayTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("play_type_code");

                    b.Property<decimal>("PrizeCostSnapshot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("prize_cost_snapshot");

                    b.Property<string>("PrizeDescriptionSnapshot")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("prize_description_snapshot");

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("uuid")
                        .HasColumnName("prize_id");

                    b.Property<string>("PrizeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prize_name_snapshot");

                    b.Property<int?>("PrizeRedeemValidDaysSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("prize_redeem_valid_days_snapshot");

                    b.Property<string>("PrizeTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("prize_tier");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_prize_awards");

                    b.HasIndex("TenantId", "DrawId", "TicketId", "LineIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_prize_awards_tenant_id_draw_id_ticket_id_line_index");

                    b.ToTable("prize_awards", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Prizes.Prize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_prizes");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_prizes_tenant_id_name");

                    b.ToTable("prizes", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.RedeemRecords.RedeemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_snapshot");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("note");

                    b.Property<Guid>("PrizeAwardId")
                        .HasColumnType("uuid")
                        .HasColumnName("prize_award_id");

                    b.Property<Guid>("PrizeId")
                        .HasColumnType("uuid")
                        .HasColumnName("prize_id");

                    b.Property<string>("PrizeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prize_name_snapshot");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_redeem_records");

                    b.HasIndex("PrizeAwardId")
                        .IsUnique()
                        .HasDatabaseName("ix_redeem_records_prize_award_id");

                    b.ToTable("redeem_records", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.TicketTemplates.TicketTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxLinesPerTicket")
                        .HasColumnType("integer")
                        .HasColumnName("max_lines_per_ticket");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_ticket_templates");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_templates_tenant_id_code");

                    b.ToTable("ticket_templates", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DrawId")
                        .HasColumnType("uuid")
                        .HasColumnName("draw_id");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_code");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("PlayTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("play_type_code");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_snapshot");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TicketTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_template_id");

                    b.Property<long>("TotalCost")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cost");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("TenantId", "MemberId", "DrawId", "CreatedAt")
                        .HasDatabaseName("ix_tickets_tenant_id_member_id_draw_id_created_at");

                    b.ToTable("tickets", "gaming");
                });

            modelBuilder.Entity("Domain.Gaming.Tickets.TicketLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("LineIndex")
                        .HasColumnType("integer")
                        .HasColumnName("line_index");

                    b.Property<string>("NumbersRaw")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("numbers_raw");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_lines");

                    b.HasIndex("TicketId", "LineIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_lines_ticket_id_line_index");

                    b.ToTable("ticket_lines", "gaming");
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_no");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_members_user_id");

                    b.HasIndex("TenantId", "MemberNo")
                        .IsUnique()
                        .HasDatabaseName("ux_members_tenant_id_member_no");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_members_tenant_id_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("members", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_member_activity_log");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_member_activity_log_action_created_at");

                    b.HasIndex("MemberId", "CreatedAt")
                        .HasDatabaseName("ix_member_activity_log_member_id_created_at");

                    b.ToTable("member_activity_log", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetBalance", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("AssetCode")
                        .HasColumnType("text")
                        .HasColumnName("asset_code");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberId", "AssetCode")
                        .HasName("pk_member_asset_balance");

                    b.ToTable("member_asset_balance", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AfterBalance")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("after_balance");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("amount");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_code");

                    b.Property<decimal>("BeforeBalance")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("before_balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_member_asset_ledger");

                    b.HasIndex("MemberId", "AssetCode", "CreatedAt")
                        .HasDatabaseName("ix_member_asset_ledger_member_id_asset_code_created_at");

                    b.ToTable("member_asset_ledger", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberPointBalance", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("MemberId")
                        .HasName("pk_member_point_balance");

                    b.ToTable("member_point_balance", "public");
                });

            modelBuilder.Entity("Domain.Members.MemberPointLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AfterBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("after_balance");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BeforeBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("before_balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("OperatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_user_id");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("text")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text")
                        .HasColumnName("reference_type");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_member_point_ledger");

                    b.HasIndex("MemberId", "CreatedAt")
                        .HasDatabaseName("ix_member_point_ledger_member_id_created_at");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_member_point_ledger_reference_type_reference_id");

                    b.ToTable("member_point_ledger", "public");
                });

            modelBuilder.Entity("Domain.Nodes.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_node");

                    b.ToTable("node", "public");
                });

            modelBuilder.Entity("Domain.Nodes.NodeRelation", b =>
                {
                    b.Property<Guid>("AncestorNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_node_id");

                    b.Property<Guid>("DescendantNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_node_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("AncestorNodeId", "DescendantNodeId")
                        .HasName("pk_node_relation");

                    b.HasIndex("DescendantNodeId")
                        .HasDatabaseName("ix_node_relation_descendant_node_id");

                    b.ToTable("node_relation", "public");
                });

            modelBuilder.Entity("Domain.Security.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups", "public");
                });

            modelBuilder.Entity("Domain.Security.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_permission_role_id");

                    b.ToTable("permission", "public");
                });

            modelBuilder.Entity("Domain.Security.PermissionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_code");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<int>("SubjectType")
                        .HasColumnType("integer")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_assignments");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_permission_assignments_node_id");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_permission_assignments_permission_code");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_permission_assignments_tenant_id");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_permission_assignments_subject_type_subject_id");

                    b.ToTable("permission_assignments", "public");
                });

            modelBuilder.Entity("Domain.Security.ResourceNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_nodes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_resource_nodes_parent_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_resource_nodes_tenant_id");

                    b.HasIndex("TenantId", "ExternalKey")
                        .IsUnique()
                        .HasDatabaseName("ux_resource_nodes_tenant_id_external_key");

                    b.ToTable("resource_nodes", "public");
                });

            modelBuilder.Entity("Domain.Security.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", "public");
                });

            modelBuilder.Entity("Domain.Security.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.HasKey("UserId", "GroupId")
                        .HasName("pk_user_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_user_groups_group_id");

                    b.HasIndex("UserId", "GroupId")
                        .HasDatabaseName("ix_user_groups_user_id_group_id");

                    b.ToTable("user_groups", "public");
                });

            modelBuilder.Entity("Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_code");

                    b.ToTable("tenants", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("HasPublicProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("has_public_profile");

                    b.Property<string>("LineUserId")
                        .HasColumnType("text")
                        .HasColumnName("line_user_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedLineUserId")
                        .HasColumnType("text")
                        .HasColumnName("normalized_line_user_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Domain.Users.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Domain.Users.User.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("CK_user_type", "\"type\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "public");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", "public");
                });

            modelBuilder.Entity("Domain.Gaming.Draws.DrawEnabledPlayType", b =>
                {
                    b.HasOne("Domain.Gaming.Draws.Draw", null)
                        .WithMany("EnabledPlayTypeItems")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_draw_enabled_play_types_draws_draw_id");
                });

            modelBuilder.Entity("Domain.Gaming.Draws.DrawPrizePoolItem", b =>
                {
                    b.HasOne("Domain.Gaming.Draws.Draw", null)
                        .WithMany("PrizePoolItems")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_draw_prize_pool_items_draws_draw_id");

                    b.HasOne("Domain.Gaming.Draws.Draw", null)
                        .WithMany("PrizePool")
                        .HasForeignKey("DrawId1")
                        .HasConstraintName("fk_draw_prize_pool_items_draws_draw_id1");

                    b.OwnsOne("Domain.Gaming.Shared.PrizeOption", "Option", b1 =>
                        {
                            b1.Property<Guid>("DrawPrizePoolItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cost")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("prize_cost_snapshot");

                            b1.Property<string>("Description")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("prize_description_snapshot");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("prize_name_snapshot");

                            b1.Property<Guid?>("PrizeId")
                                .HasColumnType("uuid")
                                .HasColumnName("prize_id_snapshot");

                            b1.Property<int?>("RedeemValidDays")
                                .HasColumnType("integer")
                                .HasColumnName("prize_redeem_valid_days_snapshot");

                            b1.HasKey("DrawPrizePoolItemId");

                            b1.ToTable("draw_prize_pool_items", "gaming");

                            b1.WithOwner()
                                .HasForeignKey("DrawPrizePoolItemId")
                                .HasConstraintName("fk_draw_prize_pool_items_draw_prize_pool_items_id");
                        });

                    b.Navigation("Option");
                });

            modelBuilder.Entity("Domain.Gaming.Tickets.TicketLine", b =>
                {
                    b.HasOne("Domain.Gaming.Tickets.Ticket", null)
                        .WithMany("Lines")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_lines_tickets_ticket_id");
                });

            modelBuilder.Entity("Domain.Members.Member", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_members_users_user_id");
                });

            modelBuilder.Entity("Domain.Members.MemberActivityLog", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_activity_log_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetBalance", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_asset_balance_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberAssetLedger", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_asset_ledger_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberPointBalance", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_point_balance_members_member_id");
                });

            modelBuilder.Entity("Domain.Members.MemberPointLedger", b =>
                {
                    b.HasOne("Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_point_ledger_members_member_id");
                });

            modelBuilder.Entity("Domain.Nodes.NodeRelation", b =>
                {
                    b.HasOne("Domain.Nodes.Node", "AncestorNode")
                        .WithMany("Descendants")
                        .HasForeignKey("AncestorNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_relation_node_ancestor_node_id");

                    b.HasOne("Domain.Nodes.Node", "DescendantNode")
                        .WithMany("Ancestors")
                        .HasForeignKey("DescendantNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_relation_node_descendant_node_id");

                    b.Navigation("AncestorNode");

                    b.Navigation("DescendantNode");
                });

            modelBuilder.Entity("Domain.Security.Permission", b =>
                {
                    b.HasOne("Domain.Security.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_permission_role_role_id");
                });

            modelBuilder.Entity("Domain.Security.PermissionAssignment", b =>
                {
                    b.HasOne("Domain.Security.ResourceNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .HasConstraintName("fk_permission_assignments_resource_nodes_node_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Domain.Security.ResourceNode", b =>
                {
                    b.HasOne("Domain.Security.ResourceNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_resource_nodes_resource_nodes_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Security.UserGroup", b =>
                {
                    b.HasOne("Domain.Security.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_groups_groups_group_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_groups_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Domain.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_role_roles_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_users_users_id");
                });

            modelBuilder.Entity("Domain.Gaming.Draws.Draw", b =>
                {
                    b.Navigation("EnabledPlayTypeItems");

                    b.Navigation("PrizePool");

                    b.Navigation("PrizePoolItems");
                });

            modelBuilder.Entity("Domain.Gaming.Tickets.Ticket", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Domain.Nodes.Node", b =>
                {
                    b.Navigation("Ancestors");

                    b.Navigation("Descendants");
                });

            modelBuilder.Entity("Domain.Security.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Domain.Security.ResourceNode", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Security.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
